#!/bin/bash

set -e

echo "pre-commit hook started"

source venv/bin/activate

pip install -r requirements.txt 1>/dev/null # stdout to dev null

python3 -m pytest

mypy **/*.py || true # Ignore failures

pylint **/*.py --rcfile=.pylintrc_test

pylint **/*.py --rcfile=.pylintrc

echo "pre-commit hook ended"
